image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-card-delivery.jar &

build_script:
  - chmod +x gradlew  # для работы с файл gradlew
  - ./gradlew test -Dselenide.headless # selenide headless режим активируется
  - # при запуске тестов с определенным параметром:
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации
